-- 코드를 입력하세요
SELECT DATE_Format(SALES_DATE, '%Y-%m-%d') as SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE Month(SALES_DATE) = 3
UNION
SELECT DATE_Format(SALES_DATE, '%Y-%m-%d') as SALES_DATE, PRODUCT_ID, Null as USER_ID, SALES_AMOUNT
FROm OFFLINE_SALE
WHERE Month(SALES_DATE) = 3
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID